### ISSUE TITLE
Typo in commands.json

### ISSUE THREAD

**Issue by jamhap64** [nicholasrobinson/SharpControlWeb#1]
In commands.json

REMOTE_POWER_OFF": "RSPWR0   \r",

I think this should be RSPW0

**Comment by nicholasrobinson** [comment]
Thanks for catching this @jamhap64 
Fix landed at [a86d7e9](https://github.com/nicholasrobinson/SharpControlWeb/commit/88ec86b0a5ce27833781ae92573c1e7d0ce88627)
